[package]
org = "tharmigan"
name = "order_processing_automation"
version = "0.1.0"
distribution = "2201.13.1"
title = "Order Processing Automation"

[build-options]
sticky = true


[[tool.persist]]
id = "order_processing_automation.ordersDB"
targetModule = "order_processing_automation.ordersDB"
filePath = "persist/ordersDB/model.bal"
options.datastore = "mysql"
options.eagerLoading = true
options.withInitParams = true

[[dependency]]
org = "ballerina"
name = "tool.persist"
version = "1.9.0"

[[dependency]]
org = "ballerinax"
name = "persist.sql"
version = "1.7.2"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.7.2"

